---
name: dev

channels:
  - defaults
  - conda-forge

dependencies:
  # Python Related
  - python=3.10             # Python version 3 and above.
  # - pyopenssl               # Handling certificates in Python. Jupyter dependency.
  # - openssl                 # Handling certificates. Python dependency.
  - pytest-cov>=3.0         # Test Python code coverage.
  - typing>=3.10            # For python type checking. Use for python 3 and above.
  # - bandit                  # Test vulnerabilities in Python code.
  # - setuptools              # Setting up Python package. Python dependency.
  # - wheel                   # Setting up Python package. Python dependency.
  # - twine                   # Deploying Python package on PYPI.
  # - line_profiler           # For code profiling runtime on cli.
  # - memory_profiler         # For code profiling runtime in files.
  # - pytz                    # Jupyter dependency.

  # Web Scraping
  # - requests                # Accessing urls. Jupyter dependency.
  - bs4                     # Beautifulsoap.

  # GitHub Related
  - git                     # Used to access GitHub.
  - hub=2.14                # Used to access GitHub.

  # IDE
  - jupyter                 # IDE
  # - ipykernel<6             # Patch for kernel restarting.
  # - tornado<5               # Jupyter dependency.
  # - jupyter_contrib_nbextensions>=0.5

  # Data Science
  - pandas>=1.5             # Data
  # - numpy<1.20              # Number calculations. Pandas dependency.
  - numpy-financial         # For financial equations
  # - scipy                   # Scientific calculations. Scikit-learn dependency.
  # - faker                   # Generates fake data

  # Databases
  - psycopg2>=2.9           # Databases
  # - sqlalchemy              # Databases
  - ijson                   # Parsing json files

  # File Types
  - openpyxl>=3.0           # Excel files in Python
  - xlrd>=2.0               # To read excel files
  - xlwt>=1.3               # To write to excel files
  # - xlsxwriter
  # - lxml>=4.9               # For parsing XML. Jupyter dependency.
  # - simplekml               # Writing KML files
  - xmltodict               # Convert XML to Dictionary
  - feedparser>=6.0         # RSS Feeds

  # **Document Files**
  - pandoc>=2.0             # Universal markup converter
  - pypdf2                  # PDF files
  # - python-docx             # Word Documents

  # Geospatial
  - geojson                 # GeoJson
  - geohash2                # Geohashes
  - shapely>=1.6            # Geos

  # Text Processing
  # - textwrap3               # Unwrap text
  - nltk>=3.5               # Natural Language Processing
  # - pyspellchecker          # Check spelling in text
  - spacy>=3.4              # NLP
  - transformers

  # Search Engine
  # - elasticsearch

  # Visualization
  - matplotlib>=3.4         # Data visualization
  - seaborn>=0.10           # Data visualization
  # - bokeh                   # Data visualization/ interaction

  # Machine Learning
  - scikit-learn>=1.0       # Machine Learning

  # Code Linters
  # - autopep8                # Formatting code
  # - yapf                    # Formatting code
  - black                   # Formatting code
  - isort>=5.0              # Formatting code
  - flake8>=3.7             # Check formatting
  - pydocstyle              # Check formatting
  - mypy>=0.6               # Check python type checking. Updated version for reveal_locals() method.

  # Sphinx Docs
  # - sphinx>=3.5             # Building sphinx docs
  # - sphinx_rtd_theme>=0.4   # Building sphinx docs
  # - nbsphinx>=0.8           # Building sphinx docs
  # - sphinx-gallery>=0.8     # Building sphinx docs

  # Makefile
  - make                    # For Makefiles

  # Graphical User Interface
  # - pysimplegui             # Graphical User Interface

  # Web Frameworks
  # - nodejs                  # Nodejs and npm

  # Flask Framework
  # - flask                   # Lightweight framework
  # - werkzeug >=0.16,<1.0    # The server Flask runs on
  # - flask-wtf               # integrates Flask and WTForms
  # - flask-restx>=0.1.1      # For Flask APIs. Replaced flask-restplus and flask-restful

  # Django Framework
  # - django                  # Heavy duty framework

  # AWS
  # - boto3

  # Anaconda Build
  # - anaconda-client         # Reaches out to Anaconda cloud
  # - conda-build             # Build conda package
  # - anaconda-project        # For projects that use Anaconda
