name: pyBase

channels:
  - defaults
  - conda-forge
  
dependencies:
  - python=3.7
  - git=2.14                # Used to access GitHub
  - hub                     # Used to access GitHub
  - jupyter                 # IDE
  - pandas                  # Data
  - numpy<2.0               # Number calculations
  - scipy                   # Scientific calculations
  - pyopenssl               # Handling certificates in Python
  - openssl                 # Handling certificates
  - openpyxl                # Handling certificates?
  - psycopg2                # Databases
  - sqlalchemy              # Databases
  - xlrd                    # To read excel files
  - xlwt                    # To write to excel files
  - lxml                    # For parsing XML
  - geojson                 # GeoJson
  - geohash2                # Geohashes
  - shapely                 # Geos
  - simplekml               # Writing KML files
  - requests                # Accessing urls
  - matplotlib              # Data visualization
  - seaborn                 # Data visualization
  - scikit-learn            # Machine Learning
  - autopep8                # Formatting code
  - flake8                  # Check formatting
  - sphinx                  # Building sphinx docs
  - sphinx_rtd_theme        # Building sphinx docs
  - pysimplegui             # Graphical User Interface
  - pytest                  # Test Python code
  - bandit                  # Test vulnerabilities in Python code
  - setuptools              # Setting up Python package
