name: pyBase
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3*
  - git
  - hub
  - jupyter
  - pandas
  - numpy
  - scipy
  - pyopenssl
  - psycopg2
  - sqlalchemy
  - xlrd
  - xlwt
  - openpyxl
  - matplotlib
  - seaborn
