name: pyBase
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3*
  - git=2.14
  - hub
  - jupyter
  - pandas
  - numpy
  - scipy
  - pyopenssl
  - psycopg2
  - sqlalchemy
  - xlrd
  - xlwt
  - openpyxl
  - matplotlib
  - seaborn
  - scikit-learn
  - requests
  - openssl
  - autopep8
  - pysimplegui
