name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:

  push:
    paths:
      - 'docs/**'

  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:

  # Continuous Integration
  # This workflow contains a single job called "build".
  build:
    name: Build

    # The type of runner that the job will run on.
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:

    # Using actions/checkout get code from repo.
    - name: GitHub Checks
      uses: actions/checkout@v2

    # Build sphinx docs.
    - name: Build docs
      run: |
        pip install sphinx sphinx_rtd_theme
        cd docs
        #make html
        make
        touch build/html/.nojekyll

    # Upload sphinx docs to GitHub Actions.
    - name: Upload docs
      uses: actions/upload-artifact@master
      with:
        name: sphinx-docs
        path: docs/build/html

  #upload:
  #  name: Upload

    # Needs the build step to pass.
  # needs: build

  #  runs-on: [ubuntu-latest]

    # Download sphinx docs from GitHub Actions.
    - name: Download docs
      uses: actions/download-artifact@master
      with:
        name: sphinx-docs
        path: docs/build/html

    # Deploy sphinx docs to GitHub.
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BRANCH: gh-pages
        FOLDER: docs/build/html
