name: my_workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:

  push:
    branches:
      - master
    #tags: 
    #  - '*'

  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Continuous Integration
  # This workflow contains a single job called "build"
  build:
    name: Build and Test

    # The type of runner that the job will run on
    #runs-on: windows-latest
    runs-on: ${{ matrix.os }}

    # Configure across different platforms
    strategy:
      matrix:

        # Windows and Linux
        os: [windows-latest]
        # ubuntu-latest

        # Python versions
        python-version: [3.5, 3.6, 3.7]
        # 2.7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Using actions/checkout for a copy of test code. 
    # Referencing actions/checkout repo. If in private repo, must reference action in private repo.
    # Syntax {owner}/{repo}@{ref}
    - uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # Check cache 
    - name: Cache pip

      # For Windows
      uses: actions/cache@v1
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache # This path is specific to Windows
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    # Build Source Distribution
    #- name: Build source distribution
    #  run: python setup.py sdist bdist_wheel

    # Format Code
    #- name: Format with Black
    #  run: |
    #    pip install black
    #    black . --check

    # Check if Flake8 compliant
    - name: Lint with flake8
      run: |
        pip install flake8
        #flake8 playground/python/package/.
        flake8 playground/python/package/ --count --select=E9,F63,F7,F82 --show-source --statistics

    # Test Code with pytest
    - name: Test with pytest
      run: |
        # pip install pytest
        # pytest comes with pytest-cov
        pip install pytest-cov
        pytest -v --cov=package python/package/geo/test/ --cov-report term-missing
        # repo-token: ${{ secrets.GITHUB_TOKEN }}
        # repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Build docs
      run: |
        pip install sphinx sphinx_rtd_theme
        cd docs
        make html
        touch build/html/.nojekyll

    - name: Upload docs
      uses: actions/upload-artifact@master
      with:
        name: sphinx-docs
        path: docs/build/html

  # Continuous Delivery
  upload:
    name: PyPI and gh-pages
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    #with:
    #      persist-credentials: false
    #- name: Download dist
    #  uses: actions/download-artifact@master
    #  with:
    #    name: pypi-dist
    #    path: dist
    #- name: Publish package
    #  uses: pypa/gh-action-pypi-publish@master
    #  with:
    #    user: __token__
    #    password: ${{ secrets.pypi_password }}
    - name: Download docs
      uses: actions/download-artifact@master
      with:
        name: sphinx-docs
        path: docs/build/html
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BRANCH: gh-pages
        FOLDER: docs/build/html
